### ISSUE TITLE
Bug/error: Error log saat akses hom_sid jika pengaturan untuk sinkronisasi ke OpenDK kosong

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#5212]
### Jelaskan error yg dialami

Terjadi error saat akses Hom_sid jika pengaturan untuk sinkronisasi ke OpenDK kosong.

### Cara untuk mereplikasi errornya

1. Kosongkan / install awal opensid baru tanpa pengaturan sinkronisasi ke OpenDK.
2. Akses menu Hom_sid
3. Cek log, muncul pesan error

### Hasil yg diharapkan

Jika tidak ada pengaturan sinkronisasi ke OpenDK lewati proses cek pesan.

### Tangkapan layar dan log error

```
ERROR - 2022-05-10 13:14:37 --> GuzzleHttp\Exception\RequestException: cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /api/v1/pesan/getpesan in D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:
#0 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\Client.php(187): GuzzleHttp\Client->requestAsync('POST', Object(GuzzleHttp\Psr7\Uri), Array)
#13 D:\OpenDesa\OpenSID\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', '/api/v1/pesan/g...', Array)
#14 D:\OpenDesa\OpenSID\donjo-app\helpers\donjolib_helper.php(758): GuzzleHttp\Client->post('/api/v1/pesan/g...', Array)
#15 D:\OpenDesa\OpenSID\donjo-app\controllers\Hom_sid.php(54): get_pesan_opendk()
#16 D:\OpenDesa\OpenSID\vendor\codeigniter\framework\system\core\CodeIgniter.php(533): Hom_sid->index()
#17 D:\OpenDesa\OpenSID\index.php(283): require_once('D:\\OpenDesa\\Ope...')
#18 {main}
```

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v22.05

### Tema Yang Digunakan

bawaan

### Informasi tambahan

.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1031
