### ISSUE TITLE
Bug/error: Aplikasi selalu mengambil data surat dari OpenDK

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#6842]
### Jelaskan error yg dialami

Akan selalu tampil error ambil data surat

### Cara untuk mereplikasi errornya

1. Masuk ke modul Permohonan Surat, modul akan melakukan request data surat ke OpenDK
2. Cek log pada modul Info Sistem > Log, akan terdapat error

### Hasil yg diharapkan

Tidak ada error tsb, jika belum ada pengaturan untuk mengaitkan data surat OpenSID ke OpenDK.

### Tangkapan layar dan log error

```
GuzzleHttp\Exception\RequestException: cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for /api/v1/surat?desa_id=18.12.08.2005 in /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:211
Stack trace:#0 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection()#1 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError()#2 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish()#3 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()#4 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()#5 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()#6 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke()#7 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()#8 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\RedirectMiddleware->__invoke()#9 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}()#10 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Client.php(333): GuzzleHttp\HandlerStack->__invoke()#11 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Client.php(169): GuzzleHttp\Client->transfer()#12 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Client->requestAsync()#13 /home/beta.opendesa.id/public_html/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()#14 /home/beta.opendesa.id/public_html/donjo-app/controllers/Keluar.php(676): GuzzleHttp\Client->get()#15 /home/beta.opendesa.id/public_html/donjo-app/controllers/Keluar.php(631): Keluar->data_kecamatan()#16 /home/beta.opendesa.id/public_html/donjo-app/controllers/Keluar.php(98): Keluar->widget()#17 /home/beta.opendesa.id/public_html/vendor/codeigniter/framework/system/core/CodeIgniter.php(533): Keluar->index()#18 /home/beta.opendesa.id/public_html/index.php(284): require_once('/home/beta.open...')#19 {
```

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2207.0.0

### Tema Yang Digunakan

bawaan

### Informasi tambahan

SUMBER : 
https://github.com/OpenSID/premium/pull/1963

SOLUSI : 
- [ ] Batasi ambil data surat dari OpenDK jika pengaturan sinkronisasi belum tersedia.
- [ ] Cek 2 bagian ini dengan kondisi di atas.
<img width="512" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/5f8e2ef6-6135-4826-a31b-bf77f571fba6">

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2588
