### ISSUE TITLE
Bug/error: Gagal melakukan passphrase

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/OpenSID#7116]
### Jelaskan error yg dialami

Tidak bisa melakukan TTE / passphrase pada surat TinyMCE

### Cara untuk mereplikasi errornya

Operator : 
1. Setting agar bisa menggunakan TTE, pastikan semua pengaturan TTE siap. Sediakan juga user Kades.
2. Lakukan cetak surat, misalkan domisili
3. Masuk ke arsip layanan, surat yg sudah dibuat lakukan persetujuan dikirim ke kades.

Kades : 
1. Masuk sebagai kades
2. Masuk ke arsip layanan, pada surat yg dikirim operator lakukan persetujuan
3. Setelah selesai, lakukan passphrase
4. Maka surat tsb akan diproses, namun yang terjadi saat ini error.

### Hasil yg diharapkan

Normal

### Tangkapan layar dan log error

<img width="490" alt="image" src="https://github.com/OpenSID/OpenSID/assets/57283157/392c411a-dae6-4613-9b2f-2589dbb4d93a">

```
ERROR - 2023-09-06 15:20:02 --> GuzzleHttp\Exception\ClientException: Client error: `POST https://devesign.************.id/api/sign/pdf` resulted in a `400 Bad Request` response:
{"error":"Proses signing gagal : com.itextpdf.text.exceptions.InvalidPdfException: Rebuild failed: Dictionary key R is n (truncated...)
 in D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113
Stack trace:
#0 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\guzzle\src\Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\promises\src\Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\guzzle\src\Client.php(189): GuzzleHttp\Promise\Promise->wait()
#10 D:\PROJECT OPENDESA\OpenSID\vendor\guzzlehttp\guzzle\src\ClientTrait.php(95): GuzzleHttp\Client->request('POST', 'api/sign/pdf', Array)
#11 D:\PROJECT OPENDESA\OpenSID\donjo-app\controllers\api\Tte.php(194): GuzzleHttp\Client->post('api/sign/pdf', Array)
#12 D:\PROJECT OPENDESA\OpenSID\vendor\codeigniter\framework\system\core\CodeIgniter.php(533): Tte->sign_visible()
#13 D:\PROJECT OPENDESA\OpenSID\index.php(284): require_once('D:\\PROJECT OPEN...')
#14 {main}
```

### Rilis Versi OpenSID

Rilis Premium

### Versi OpenSID

v2309.0.0

### Tema Yang Digunakan

bawaan

### Informasi tambahan

Dari notifikasi, sepertinya terjadi kerusakan pada file yang akan dikirim ke server ESign

**Comment by andifahruddinakas** [comment]
Database dan server esign terlampir di gdrive opendesa

**Comment by agungsugiarto** [comment]
yg di coba ini surat apa mas @andifahruddinakas ?

**Comment by andifahruddinakas** [comment]
> yg di coba ini surat apa mas @andifahruddinakas ?

Coba dibaca dlu keterangan alurnya di issue sampai dapat error. Di alur sudah jelas menggunakan surat domisili

**Comment by agungsugiarto** [comment]
status issue ini menunggu pembaharuan server dev esign

**Comment by andifahruddinakas** [comment]
mas @agungsugiarto, sudah bisa di lanjutkan.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/2967
