### ISSUE TITLE
Bug/error: Blank 500 Error

### ISSUE THREAD

**Issue by ndunks** [OpenSID/OpenSID#8416]
### Jelaskan error yg dialami

Terjadi blank 500 ERROR setelah merge/upgrade ke 2408 dari 23xx

![image](https://github.com/user-attachments/assets/20dbe861-c9eb-4d8b-8443-2ae496feb7cd)

### Cara untuk mereplikasi errornya

update lompat versi, buka home page

### Hasil yg diharapkan

Setelah di remove class MY_Exection, baru muncul.. nanti aku PR aja ya buat kondisional

![image](https://github.com/user-attachments/assets/452ea409-6ee1-4be7-910a-209b2684499a)

### Tangkapan layar dan log error

```
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class 'CI_Controller' not found in /var/www/***/vendor/codeigniter/framework/system/core/CodeIgniter.php:370"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "Stack trace:"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#0 /var/www/***/donjo-app/core/MY_Exceptions.php(58): get_instance()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#1 /var/www/***/vendor/codeigniter/framework/system/core/Common.php(197): MY_Exceptions->__construct()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#2 /var/www/***/vendor/codeigniter/framework/system/core/Common.php(653): load_class()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#3 [internal function]: _exception_handler()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#4 {main}"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "  thrown in /var/www/***/vendor/codeigniter/framework/system/core/CodeIgniter.php on line 370"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class 'CI_Controller' not found in /var/www/***/vendor/codeigniter/framework/system/core/CodeIgniter.php:370"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "Stack trace:"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#0 /var/www/***/donjo-app/core/MY_Exceptions.php(58): get_instance()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#1 /var/www/***/vendor/codeigniter/framework/system/core/Common.php(197): MY_Exceptions->__construct()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#2 /var/www/***/vendor/codeigniter/framework/system/core/Common.php(618): load_class()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#3 /var/www/***/vendor/codeigniter/framework/system/core/Common.php(690): _error_handler()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#4 [internal function]: _shutdown_handler()"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "#5 {main}"
[31-Aug-2024 09:18:09] WARNING: [pool www] child 25499 said into stderr: "  thrown in /var/www/***/vendor/codeigniter/framework/system/core/CodeIgniter.php on line 370"
[31-Aug-2024 09:19:10] WARNING: [pool www] child 25018 said into stderr: "NOTICE: PHP message: Silakan upgrade dulu ke OpenSID dengan minimal versi 2407"
```
Ternyata krna di custom class MY_Exception ada manggil fungsi `get_instance`, sedangkan class `CI_Controller` blm ready.. 

### Rilis Versi OpenSID

Rilis Umum

### Versi OpenSID

2408

**Comment by ndunks** [comment]
Note: sudah coba upgrade dari 2407 ke 2408, tapi tetap dapat error seperti ini:

![image](https://github.com/user-attachments/assets/622bf04b-e26a-4ef7-9a41-bd819ac556ae)

**Comment by andifahruddinakas** [comment]
ini mas @ndunks, 
https://forum.opendesa.id/d/341-error-ketika-update-dari-2407-versi-umum-ke-2408-versi-umum

**Comment by ndunks** [comment]
Ini sbnernya bukan update gagal yg dibikin issue, tpi error messagenya yg nggak tampil, sehingga butuh waktu lebih lama untuk mengetahui penyebab errornya.. terjadi error ketika mau menampilkan pesan error, ya terserah aja si nggak di merge juga gpp, aku udah open PR ini
